cd ../classification
python run_classifiers.py --hyperparams optimal_technical --anomalies 5 --base nb --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 10 --base nb --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 20 --base nb --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 25 --base nb --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 30 --base nb --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 40 --base nb --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 50 --base nb --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 100 --base nb --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 5 --base mlp --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 10 --base mlp --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 20 --base mlp --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 25 --base mlp --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 30 --base mlp --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 40 --base mlp --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 50 --base mlp --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 100 --base mlp --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 5 --base svc --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 10 --base svc --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 20 --base svc --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 25 --base svc --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 30 --base svc --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 40 --base svc --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 50 --base svc --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 100 --base svc --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 5 --base knn --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 10 --base knn --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 20 --base knn --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 25 --base knn --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 30 --base knn --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 40 --base knn --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 50 --base knn --generator-method cvae cinn
python run_classifiers.py --hyperparams optimal_technical --anomalies 100 --base knn --generator-method cvae cinn